name: Build PlatformIO Project
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build PlatformIO Project
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Cache
        uses: actions/cache@v5.0.4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Set Up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.14"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        shell: bash

      - name: Build PlatformIO Project
        run: pio run
        shell: bash
